### ISSUE TITLE
clone is too slow

### ISSUE THREAD

**Issue by neo1218** [Leo-G/Flask-Scaffold#18]
In particular I am Chinese。。。

**Comment by Leo-G** [comment]
The issue could be due to Github throttling connections from China, I will setup auto deploy to heroku shortly you can use that if you like

**Comment by neo1218** [comment]
Thx, I got it.
Flask-Scaffold is excellent， it just like django, I think we can more easily build large projects by flask use Flask-Scaffold!

**Comment by Leo-G** [comment]
Thanks neo1218, You are absolutely correct. :)
