### ISSUE TITLE
Why not using AdminLTE as ui template?

### ISSUE THREAD

**Issue by copuzzle** [Leo-G/Flask-Scaffold#21]
AdminLTE is a open source admin ui template.there https://github.com/almasaeed2010/AdminLTE
I thought it is a good idea to use it for this project .
what you think?

**Comment by Leo-G** [comment]
@copuzzle That's a nice template, if you can help figure out how to connect it with the backend API, I think we can include this option as well.

**Comment by copuzzle** [comment]
@Leo-G OK, I will try.

**Comment by Althea-Lobo** [comment]
Great, Looking forward to your contribution :)

**Comment by wavemaking** [comment]
ng-admin may be another good fit

**Comment by Leo-G** [comment]
@wavemaking That's a good idea, can you help to add it?

**Comment by wavemaking** [comment]
Well I'm currently figuring out all these technologies, Flask, AngularJS, etc. for a hobby project. I'll consider picking this up when I get to grip with things. But I'm not quite there yet..

**Comment by Leo-G** [comment]
@wavemaking porting ng-admin to Flask-Scaffold will be the best way to learn :) I learnt an incredible lot about Flask, SQLALchemy, Angularjs, Protractor and I only wanted to learn about Python :)

**Comment by Leo-G** [comment]
Currently AdminLTE uses jquery and this project is based on Angularjs, To use AdminLTE a lot of code will have to be revamped including the routes hence for now this will not be part of the road map
