### ISSUE TITLE
Pypy not supported

### ISSUE THREAD

**Issue by zypeh** [Leo-G/Flask-Scaffold#23]
According to [this](https://bitbucket.org/pypy/pypy/issues/997). This repo can't be built on Pypy implementation because of the `pycrypto` package. Which is not suitable for deployment :disappointed: 

Any idea to do so ?
## edit

added package that can't be compiled on Pypy.

**Comment by Leo-G** [comment]
I am using Pyjwt for JSON token auth and I believe pycrpto is a dependency for the token hash, Any specific you reason you are using Pypy as I don't see this as a priority feature at the moment

**Comment by Leo-G** [comment]
no reply hence closing
