### ISSUE TITLE
flask-restful blueprints can only be registered once.

### ISSUE THREAD

**Issue by mvmthecreator** [Leo-G/Flask-Scaffold#32]
i have run this command `python scaffold.py scaffold/blog.yaml`. then i run` python db.py db init` and gives the following error: `ValueError: flask-restful blueprints can only be registered once.
`

**Comment by Leo-G** [comment]
check app/__init__.py for "app.register_blueprint" , there must be a duplicate registration. If still confused share app/__init__.py here
