### ISSUE TITLE
Errors in scaffold/app/models.py

### ISSUE THREAD

**Issue by RutujaWanjari** [Leo-G/Flask-Scaffold#34]
Hello Leo,
I am new to python. Maybe I am not getting syntax properly but this file (scaffold/app/models.py)  shows errors. PFA,
![screenshot from 2018-01-18 15-25-10](https://user-images.githubusercontent.com/19467081/35085540-13dc35c2-fc64-11e7-8466-f2e9b061086c.png)

**Comment by Leo-G** [comment]
Well  its actually not a python file, its used to create a python file  replacing the fields/blanks in the curl brackets,  the real python files will be in the 'app' folder not the in the 'scaffold' folder

**Comment by RutujaWanjari** [comment]
Oh I see. Thank you. Its a great repo.
