### ISSUE TITLE
Need to rectify README to denote 'users' instead of 'posts'

### ISSUE THREAD

**Issue by pmk1433** [Leo-g/Flask-Scaffold#7]
In the Scaffold section of the README, it talks about the 'posts' whereas it should actually be 'users'. 

Otherwise it is a most excellent intro tutorial for Flask using SQLAlchemy. Hats off to you Leo!

**Comment by Leo-g** [comment]
Nope, Users is already there https://github.com/Leo-g/Flask-Skeleton/tree/master/app/users

Thanks

**Comment by pmk1433** [comment]
Leo,
              I was talking about the readme file. It still has 'posts' in
the Scaffold section while your example is talking about 'users'.

Regards,
Krishnan

**Comment by Leo-g** [comment]
Hi Krishnan,

I understand what you are saying, I have updated the https://github.com/Leo-g/Flask-Scaffold/blob/master/README.md completely can you check now

**Comment by pmk1433** [comment]
Yes, it looks better now. Thank you so much for sharing your posts/code on Flask. It was really useful for me!

**Comment by Leo-g** [comment]
Your welcome, Do join the community https://plus.google.com/u/0/b/104889801713275137574/communities/109010680875664603632 
Would also love to see more contributions from you :)
